//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmashSoft.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", ConfigurationName="ServicioWS.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarPorNombreRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmashSoft.ServicioWS.listarPorNombreResponse listarPorNombre(SmashSoft.ServicioWS.listarPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarPorNombreRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarPorNombreResponse")]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarPorNombreResponse> listarPorNombreAsync(SmashSoft.ServicioWS.listarPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarTodasRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmashSoft.ServicioWS.listarTodasResponse listarTodas(SmashSoft.ServicioWS.listarTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarTodasRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/listarTodasResponse")]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarTodasResponse> listarTodasAsync(SmashSoft.ServicioWS.listarTodasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/insertarRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/insertarResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SmashSoft.ServicioWS.insertarResponse insertar(SmashSoft.ServicioWS.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.smashsoft.pucp.edu.pe/ServicioWS/insertarRequest", ReplyAction="http://services.smashsoft.pucp.edu.pe/ServicioWS/insertarResponse")]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.insertarResponse> insertarAsync(SmashSoft.ServicioWS.insertarRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/")]
    public partial class universo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idUniversoField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idUniverso {
            get {
                return this.idUniversoField;
            }
            set {
                this.idUniversoField = value;
                this.RaisePropertyChanged("idUniverso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/")]
    public partial class personaje : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool adhesionParedesField;
        
        private bool arrastreField;
        
        private int cantidadMaxSaltosField;
        
        private string descripcionField;
        
        private System.DateTime fechaAparicionField;
        
        private bool fechaAparicionFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPersonajeField;
        
        private string nombreField;
        
        private double pesoField;
        
        private plataforma plataformaField;
        
        private bool saltoParedField;
        
        private universo universoField;
        
        private double velocidadAlCaminarField;
        
        private double velocidadAlCorrerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool adhesionParedes {
            get {
                return this.adhesionParedesField;
            }
            set {
                this.adhesionParedesField = value;
                this.RaisePropertyChanged("adhesionParedes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool arrastre {
            get {
                return this.arrastreField;
            }
            set {
                this.arrastreField = value;
                this.RaisePropertyChanged("arrastre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantidadMaxSaltos {
            get {
                return this.cantidadMaxSaltosField;
            }
            set {
                this.cantidadMaxSaltosField = value;
                this.RaisePropertyChanged("cantidadMaxSaltos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaAparicion {
            get {
                return this.fechaAparicionField;
            }
            set {
                this.fechaAparicionField = value;
                this.RaisePropertyChanged("fechaAparicion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaAparicionSpecified {
            get {
                return this.fechaAparicionFieldSpecified;
            }
            set {
                this.fechaAparicionFieldSpecified = value;
                this.RaisePropertyChanged("fechaAparicionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=5)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idPersonaje {
            get {
                return this.idPersonajeField;
            }
            set {
                this.idPersonajeField = value;
                this.RaisePropertyChanged("idPersonaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("peso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public plataforma plataforma {
            get {
                return this.plataformaField;
            }
            set {
                this.plataformaField = value;
                this.RaisePropertyChanged("plataforma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool saltoPared {
            get {
                return this.saltoParedField;
            }
            set {
                this.saltoParedField = value;
                this.RaisePropertyChanged("saltoPared");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public universo universo {
            get {
                return this.universoField;
            }
            set {
                this.universoField = value;
                this.RaisePropertyChanged("universo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public double velocidadAlCaminar {
            get {
                return this.velocidadAlCaminarField;
            }
            set {
                this.velocidadAlCaminarField = value;
                this.RaisePropertyChanged("velocidadAlCaminar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public double velocidadAlCorrer {
            get {
                return this.velocidadAlCorrerField;
            }
            set {
                this.velocidadAlCorrerField = value;
                this.RaisePropertyChanged("velocidadAlCorrer");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/")]
    public partial class plataforma : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int idPlataformaField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idPlataforma {
            get {
                return this.idPlataformaField;
            }
            set {
                this.idPlataformaField = value;
                this.RaisePropertyChanged("idPlataforma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombre", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarPorNombreRequest() {
        }
        
        public listarPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreResponse", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmashSoft.ServicioWS.universo[] @return;
        
        public listarPorNombreResponse() {
        }
        
        public listarPorNombreResponse(SmashSoft.ServicioWS.universo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodas", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasRequest {
        
        public listarTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasResponse", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmashSoft.ServicioWS.plataforma[] @return;
        
        public listarTodasResponse() {
        }
        
        public listarTodasResponse(SmashSoft.ServicioWS.plataforma[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SmashSoft.ServicioWS.personaje personaje;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SmashSoft.ServicioWS.personaje personaje) {
            this.personaje = personaje;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.smashsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.smashsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : SmashSoft.ServicioWS.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<SmashSoft.ServicioWS.ServicioWS>, SmashSoft.ServicioWS.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmashSoft.ServicioWS.listarPorNombreResponse SmashSoft.ServicioWS.ServicioWS.listarPorNombre(SmashSoft.ServicioWS.listarPorNombreRequest request) {
            return base.Channel.listarPorNombre(request);
        }
        
        public SmashSoft.ServicioWS.universo[] listarPorNombre(string nombre) {
            SmashSoft.ServicioWS.listarPorNombreRequest inValue = new SmashSoft.ServicioWS.listarPorNombreRequest();
            inValue.nombre = nombre;
            SmashSoft.ServicioWS.listarPorNombreResponse retVal = ((SmashSoft.ServicioWS.ServicioWS)(this)).listarPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarPorNombreResponse> SmashSoft.ServicioWS.ServicioWS.listarPorNombreAsync(SmashSoft.ServicioWS.listarPorNombreRequest request) {
            return base.Channel.listarPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarPorNombreResponse> listarPorNombreAsync(string nombre) {
            SmashSoft.ServicioWS.listarPorNombreRequest inValue = new SmashSoft.ServicioWS.listarPorNombreRequest();
            inValue.nombre = nombre;
            return ((SmashSoft.ServicioWS.ServicioWS)(this)).listarPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmashSoft.ServicioWS.listarTodasResponse SmashSoft.ServicioWS.ServicioWS.listarTodas(SmashSoft.ServicioWS.listarTodasRequest request) {
            return base.Channel.listarTodas(request);
        }
        
        public SmashSoft.ServicioWS.plataforma[] listarTodas() {
            SmashSoft.ServicioWS.listarTodasRequest inValue = new SmashSoft.ServicioWS.listarTodasRequest();
            SmashSoft.ServicioWS.listarTodasResponse retVal = ((SmashSoft.ServicioWS.ServicioWS)(this)).listarTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarTodasResponse> SmashSoft.ServicioWS.ServicioWS.listarTodasAsync(SmashSoft.ServicioWS.listarTodasRequest request) {
            return base.Channel.listarTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmashSoft.ServicioWS.listarTodasResponse> listarTodasAsync() {
            SmashSoft.ServicioWS.listarTodasRequest inValue = new SmashSoft.ServicioWS.listarTodasRequest();
            return ((SmashSoft.ServicioWS.ServicioWS)(this)).listarTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SmashSoft.ServicioWS.insertarResponse SmashSoft.ServicioWS.ServicioWS.insertar(SmashSoft.ServicioWS.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SmashSoft.ServicioWS.personaje personaje) {
            SmashSoft.ServicioWS.insertarRequest inValue = new SmashSoft.ServicioWS.insertarRequest();
            inValue.personaje = personaje;
            SmashSoft.ServicioWS.insertarResponse retVal = ((SmashSoft.ServicioWS.ServicioWS)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SmashSoft.ServicioWS.insertarResponse> SmashSoft.ServicioWS.ServicioWS.insertarAsync(SmashSoft.ServicioWS.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SmashSoft.ServicioWS.insertarResponse> insertarAsync(SmashSoft.ServicioWS.personaje personaje) {
            SmashSoft.ServicioWS.insertarRequest inValue = new SmashSoft.ServicioWS.insertarRequest();
            inValue.personaje = personaje;
            return ((SmashSoft.ServicioWS.ServicioWS)(this)).insertarAsync(inValue);
        }
    }
}
