//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSoft.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", ConfigurationName="ServicioWeb.ServicioWeb")]
    public interface ServicioWeb {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarMovimientosNivelPorIDReque" +
            "st", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarMovimientosNivelPorIDRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse listarMovimientosNivelPorID(GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarMovimientosNivelPorIDReque" +
            "st", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarMovimientosNivelPorIDRespo" +
            "nse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse> listarMovimientosNivelPorIDAsync(GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/insertarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/insertarPokemonResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.insertarPokemonResponse insertarPokemon(GameSoft.ServicioWeb.insertarPokemonRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/insertarPokemonRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/insertarPokemonResponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.insertarPokemonResponse> insertarPokemonAsync(GameSoft.ServicioWeb.insertarPokemonRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarPokemonesPorNombreRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarPokemonesPorNombreResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.listarPokemonesPorNombreResponse listarPokemonesPorNombre(GameSoft.ServicioWeb.listarPokemonesPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarPokemonesPorNombreRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarPokemonesPorNombreResponse" +
            "")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarPokemonesPorNombreResponse> listarPokemonesPorNombreAsync(GameSoft.ServicioWeb.listarPokemonesPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodasClasesRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodasClasesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.listarTodasClasesResponse listarTodasClases(GameSoft.ServicioWeb.listarTodasClasesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodasClasesRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodasClasesResponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodasClasesResponse> listarTodasClasesAsync(GameSoft.ServicioWeb.listarTodasClasesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodosTiposElementalesReque" +
            "st", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodosTiposElementalesRespo" +
            "nse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.listarTodosTiposElementalesResponse listarTodosTiposElementales(GameSoft.ServicioWeb.listarTodosTiposElementalesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodosTiposElementalesReque" +
            "st", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarTodosTiposElementalesRespo" +
            "nse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodosTiposElementalesResponse> listarTodosTiposElementalesAsync(GameSoft.ServicioWeb.listarTodosTiposElementalesRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarBlancosPorNombreRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarBlancosPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWeb.listarBlancosPorNombreResponse listarBlancosPorNombre(GameSoft.ServicioWeb.listarBlancosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarBlancosPorNombreRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWeb/listarBlancosPorNombreResponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarBlancosPorNombreResponse> listarBlancosPorNombreAsync(GameSoft.ServicioWeb.listarBlancosPorNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class movimientoNivel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private blanco blancoField;
        
        private clase claseField;
        
        private int exactitudField;
        
        private int idMovimientoNivelField;
        
        private int nivelAprendizajeField;
        
        private string nombreMovimientoField;
        
        private int poderField;
        
        private int puntosPoderField;
        
        private tipoElemental tipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public blanco blanco {
            get {
                return this.blancoField;
            }
            set {
                this.blancoField = value;
                this.RaisePropertyChanged("blanco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public clase clase {
            get {
                return this.claseField;
            }
            set {
                this.claseField = value;
                this.RaisePropertyChanged("clase");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int exactitud {
            get {
                return this.exactitudField;
            }
            set {
                this.exactitudField = value;
                this.RaisePropertyChanged("exactitud");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idMovimientoNivel {
            get {
                return this.idMovimientoNivelField;
            }
            set {
                this.idMovimientoNivelField = value;
                this.RaisePropertyChanged("idMovimientoNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int nivelAprendizaje {
            get {
                return this.nivelAprendizajeField;
            }
            set {
                this.nivelAprendizajeField = value;
                this.RaisePropertyChanged("nivelAprendizaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreMovimiento {
            get {
                return this.nombreMovimientoField;
            }
            set {
                this.nombreMovimientoField = value;
                this.RaisePropertyChanged("nombreMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public int poder {
            get {
                return this.poderField;
            }
            set {
                this.poderField = value;
                this.RaisePropertyChanged("poder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public int puntosPoder {
            get {
                return this.puntosPoderField;
            }
            set {
                this.puntosPoderField = value;
                this.RaisePropertyChanged("puntosPoder");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public tipoElemental tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class blanco : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string blancoMovimientoField;
        
        private string descripcionField;
        
        private int idBlancoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string blancoMovimiento {
            get {
                return this.blancoMovimientoField;
            }
            set {
                this.blancoMovimientoField = value;
                this.RaisePropertyChanged("blancoMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idBlanco {
            get {
                return this.idBlancoField;
            }
            set {
                this.idBlancoField = value;
                this.RaisePropertyChanged("idBlanco");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class pokemon : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private double alturaField;
        
        private string descripcionField;
        
        private byte[] fotoField;
        
        private generacion generacionField;
        
        private bool generacionFieldSpecified;
        
        private int idPokemonField;
        
        private movimientoNivel[] movimientosNivelField;
        
        private string nombreField;
        
        private string numeroPokedexNacionalField;
        
        private double pesoField;
        
        private tipoElemental tipo1Field;
        
        private tipoElemental tipo2Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=3)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public generacion generacion {
            get {
                return this.generacionField;
            }
            set {
                this.generacionField = value;
                this.RaisePropertyChanged("generacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool generacionSpecified {
            get {
                return this.generacionFieldSpecified;
            }
            set {
                this.generacionFieldSpecified = value;
                this.RaisePropertyChanged("generacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idPokemon {
            get {
                return this.idPokemonField;
            }
            set {
                this.idPokemonField = value;
                this.RaisePropertyChanged("idPokemon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("movimientosNivel", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=6)]
        public movimientoNivel[] movimientosNivel {
            get {
                return this.movimientosNivelField;
            }
            set {
                this.movimientosNivelField = value;
                this.RaisePropertyChanged("movimientosNivel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string numeroPokedexNacional {
            get {
                return this.numeroPokedexNacionalField;
            }
            set {
                this.numeroPokedexNacionalField = value;
                this.RaisePropertyChanged("numeroPokedexNacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public double peso {
            get {
                return this.pesoField;
            }
            set {
                this.pesoField = value;
                this.RaisePropertyChanged("peso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public tipoElemental tipo1 {
            get {
                return this.tipo1Field;
            }
            set {
                this.tipo1Field = value;
                this.RaisePropertyChanged("tipo1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoElemental tipo2 {
            get {
                return this.tipo2Field;
            }
            set {
                this.tipo2Field = value;
                this.RaisePropertyChanged("tipo2");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public enum generacion {
        
        /// <remarks/>
        PRIMERA_GENERACION,
        
        /// <remarks/>
        SEGUNDA_GENERACION,
        
        /// <remarks/>
        TERCERA_GENERACION,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class tipoElemental : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private byte[] fotoField;
        
        private int idTipoElementalField;
        
        private string nombreField;
        
        private int valorAzulField;
        
        private int valorRojoField;
        
        private int valorVerdeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoElemental {
            get {
                return this.idTipoElementalField;
            }
            set {
                this.idTipoElementalField = value;
                this.RaisePropertyChanged("idTipoElemental");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int valorAzul {
            get {
                return this.valorAzulField;
            }
            set {
                this.valorAzulField = value;
                this.RaisePropertyChanged("valorAzul");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int valorRojo {
            get {
                return this.valorRojoField;
            }
            set {
                this.valorRojoField = value;
                this.RaisePropertyChanged("valorRojo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int valorVerde {
            get {
                return this.valorVerdeField;
            }
            set {
                this.valorVerdeField = value;
                this.RaisePropertyChanged("valorVerde");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class clase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string claseMovimientoField;
        
        private byte[] fotoField;
        
        private int idClaseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string claseMovimiento {
            get {
                return this.claseMovimientoField;
            }
            set {
                this.claseMovimientoField = value;
                this.RaisePropertyChanged("claseMovimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idClase {
            get {
                return this.idClaseField;
            }
            set {
                this.idClaseField = value;
                this.RaisePropertyChanged("idClase");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMovimientosNivelPorID", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMovimientosNivelPorIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idPokemon;
        
        public listarMovimientosNivelPorIDRequest() {
        }
        
        public listarMovimientosNivelPorIDRequest(int idPokemon) {
            this.idPokemon = idPokemon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarMovimientosNivelPorIDResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarMovimientosNivelPorIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.movimientoNivel[] @return;
        
        public listarMovimientosNivelPorIDResponse() {
        }
        
        public listarMovimientosNivelPorIDResponse(GameSoft.ServicioWeb.movimientoNivel[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemon", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.pokemon pokemon;
        
        public insertarPokemonRequest() {
        }
        
        public insertarPokemonRequest(GameSoft.ServicioWeb.pokemon pokemon) {
            this.pokemon = pokemon;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPokemonResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarPokemonResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPokemonResponse() {
        }
        
        public insertarPokemonResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemonesPorNombre", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonesPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarPokemonesPorNombreRequest() {
        }
        
        public listarPokemonesPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPokemonesPorNombreResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPokemonesPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.pokemon[] @return;
        
        public listarPokemonesPorNombreResponse() {
        }
        
        public listarPokemonesPorNombreResponse(GameSoft.ServicioWeb.pokemon[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClases", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasClasesRequest {
        
        public listarTodasClasesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasClasesResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasClasesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.clase[] @return;
        
        public listarTodasClasesResponse() {
        }
        
        public listarTodasClasesResponse(GameSoft.ServicioWeb.clase[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTiposElementales", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposElementalesRequest {
        
        public listarTodosTiposElementalesRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosTiposElementalesResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosTiposElementalesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.tipoElemental[] @return;
        
        public listarTodosTiposElementalesResponse() {
        }
        
        public listarTodosTiposElementalesResponse(GameSoft.ServicioWeb.tipoElemental[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBlancosPorNombre", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBlancosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarBlancosPorNombreRequest() {
        }
        
        public listarBlancosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarBlancosPorNombreResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarBlancosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWeb.blanco[] @return;
        
        public listarBlancosPorNombreResponse() {
        }
        
        public listarBlancosPorNombreResponse(GameSoft.ServicioWeb.blanco[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebChannel : GameSoft.ServicioWeb.ServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<GameSoft.ServicioWeb.ServicioWeb>, GameSoft.ServicioWeb.ServicioWeb {
        
        public ServicioWebClient() {
        }
        
        public ServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse GameSoft.ServicioWeb.ServicioWeb.listarMovimientosNivelPorID(GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest request) {
            return base.Channel.listarMovimientosNivelPorID(request);
        }
        
        public GameSoft.ServicioWeb.movimientoNivel[] listarMovimientosNivelPorID(int idPokemon) {
            GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest inValue = new GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest();
            inValue.idPokemon = idPokemon;
            GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarMovimientosNivelPorID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse> GameSoft.ServicioWeb.ServicioWeb.listarMovimientosNivelPorIDAsync(GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest request) {
            return base.Channel.listarMovimientosNivelPorIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarMovimientosNivelPorIDResponse> listarMovimientosNivelPorIDAsync(int idPokemon) {
            GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest inValue = new GameSoft.ServicioWeb.listarMovimientosNivelPorIDRequest();
            inValue.idPokemon = idPokemon;
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarMovimientosNivelPorIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.insertarPokemonResponse GameSoft.ServicioWeb.ServicioWeb.insertarPokemon(GameSoft.ServicioWeb.insertarPokemonRequest request) {
            return base.Channel.insertarPokemon(request);
        }
        
        public int insertarPokemon(GameSoft.ServicioWeb.pokemon pokemon) {
            GameSoft.ServicioWeb.insertarPokemonRequest inValue = new GameSoft.ServicioWeb.insertarPokemonRequest();
            inValue.pokemon = pokemon;
            GameSoft.ServicioWeb.insertarPokemonResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).insertarPokemon(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.insertarPokemonResponse> GameSoft.ServicioWeb.ServicioWeb.insertarPokemonAsync(GameSoft.ServicioWeb.insertarPokemonRequest request) {
            return base.Channel.insertarPokemonAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.insertarPokemonResponse> insertarPokemonAsync(GameSoft.ServicioWeb.pokemon pokemon) {
            GameSoft.ServicioWeb.insertarPokemonRequest inValue = new GameSoft.ServicioWeb.insertarPokemonRequest();
            inValue.pokemon = pokemon;
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).insertarPokemonAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.listarPokemonesPorNombreResponse GameSoft.ServicioWeb.ServicioWeb.listarPokemonesPorNombre(GameSoft.ServicioWeb.listarPokemonesPorNombreRequest request) {
            return base.Channel.listarPokemonesPorNombre(request);
        }
        
        public GameSoft.ServicioWeb.pokemon[] listarPokemonesPorNombre(string nombre) {
            GameSoft.ServicioWeb.listarPokemonesPorNombreRequest inValue = new GameSoft.ServicioWeb.listarPokemonesPorNombreRequest();
            inValue.nombre = nombre;
            GameSoft.ServicioWeb.listarPokemonesPorNombreResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarPokemonesPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarPokemonesPorNombreResponse> GameSoft.ServicioWeb.ServicioWeb.listarPokemonesPorNombreAsync(GameSoft.ServicioWeb.listarPokemonesPorNombreRequest request) {
            return base.Channel.listarPokemonesPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarPokemonesPorNombreResponse> listarPokemonesPorNombreAsync(string nombre) {
            GameSoft.ServicioWeb.listarPokemonesPorNombreRequest inValue = new GameSoft.ServicioWeb.listarPokemonesPorNombreRequest();
            inValue.nombre = nombre;
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarPokemonesPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.listarTodasClasesResponse GameSoft.ServicioWeb.ServicioWeb.listarTodasClases(GameSoft.ServicioWeb.listarTodasClasesRequest request) {
            return base.Channel.listarTodasClases(request);
        }
        
        public GameSoft.ServicioWeb.clase[] listarTodasClases() {
            GameSoft.ServicioWeb.listarTodasClasesRequest inValue = new GameSoft.ServicioWeb.listarTodasClasesRequest();
            GameSoft.ServicioWeb.listarTodasClasesResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarTodasClases(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodasClasesResponse> GameSoft.ServicioWeb.ServicioWeb.listarTodasClasesAsync(GameSoft.ServicioWeb.listarTodasClasesRequest request) {
            return base.Channel.listarTodasClasesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodasClasesResponse> listarTodasClasesAsync() {
            GameSoft.ServicioWeb.listarTodasClasesRequest inValue = new GameSoft.ServicioWeb.listarTodasClasesRequest();
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarTodasClasesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.listarTodosTiposElementalesResponse GameSoft.ServicioWeb.ServicioWeb.listarTodosTiposElementales(GameSoft.ServicioWeb.listarTodosTiposElementalesRequest request) {
            return base.Channel.listarTodosTiposElementales(request);
        }
        
        public GameSoft.ServicioWeb.tipoElemental[] listarTodosTiposElementales() {
            GameSoft.ServicioWeb.listarTodosTiposElementalesRequest inValue = new GameSoft.ServicioWeb.listarTodosTiposElementalesRequest();
            GameSoft.ServicioWeb.listarTodosTiposElementalesResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarTodosTiposElementales(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodosTiposElementalesResponse> GameSoft.ServicioWeb.ServicioWeb.listarTodosTiposElementalesAsync(GameSoft.ServicioWeb.listarTodosTiposElementalesRequest request) {
            return base.Channel.listarTodosTiposElementalesAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarTodosTiposElementalesResponse> listarTodosTiposElementalesAsync() {
            GameSoft.ServicioWeb.listarTodosTiposElementalesRequest inValue = new GameSoft.ServicioWeb.listarTodosTiposElementalesRequest();
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarTodosTiposElementalesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWeb.listarBlancosPorNombreResponse GameSoft.ServicioWeb.ServicioWeb.listarBlancosPorNombre(GameSoft.ServicioWeb.listarBlancosPorNombreRequest request) {
            return base.Channel.listarBlancosPorNombre(request);
        }
        
        public GameSoft.ServicioWeb.blanco[] listarBlancosPorNombre(string nombre) {
            GameSoft.ServicioWeb.listarBlancosPorNombreRequest inValue = new GameSoft.ServicioWeb.listarBlancosPorNombreRequest();
            inValue.nombre = nombre;
            GameSoft.ServicioWeb.listarBlancosPorNombreResponse retVal = ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarBlancosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarBlancosPorNombreResponse> GameSoft.ServicioWeb.ServicioWeb.listarBlancosPorNombreAsync(GameSoft.ServicioWeb.listarBlancosPorNombreRequest request) {
            return base.Channel.listarBlancosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWeb.listarBlancosPorNombreResponse> listarBlancosPorNombreAsync(string nombre) {
            GameSoft.ServicioWeb.listarBlancosPorNombreRequest inValue = new GameSoft.ServicioWeb.listarBlancosPorNombreRequest();
            inValue.nombre = nombre;
            return ((GameSoft.ServicioWeb.ServicioWeb)(this)).listarBlancosPorNombreAsync(inValue);
        }
    }
}
