//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProductions.SoftProductionsWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", ConfigurationName="SoftProductionsWS.SoftProductionsWS")]
    public interface SoftProductionsWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodosDirector" +
            "esRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodosDirector" +
            "esResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse listarTodosDirectores(SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodosDirector" +
            "esRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodosDirector" +
            "esResponse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse> listarTodosDirectoresAsync(SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWS.listarTodasProductorasResponse listarTodasProductoras(SoftProductions.SoftProductionsWS.listarTodasProductorasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasRequest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarTodasProducto" +
            "rasResponse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodasProductorasResponse> listarTodasProductorasAsync(SoftProductions.SoftProductionsWS.listarTodasProductorasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarCapitulosXIDR" +
            "equest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarCapitulosXIDR" +
            "esponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse listarCapitulosXID(SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarCapitulosXIDR" +
            "equest", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarCapitulosXIDR" +
            "esponse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse> listarCapitulosXIDAsync(SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Request", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse listarSeriesXNombre(SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Request", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/listarSeriesXNombre" +
            "Response")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse> listarSeriesXNombreAsync(SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieTVRequ" +
            "est", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieTVResp" +
            "onse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.SoftProductionsWS.insertarSerieTVResponse insertarSerieTV(SoftProductions.SoftProductionsWS.insertarSerieTVRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieTVRequ" +
            "est", ReplyAction="http://services.softproductions.pucp.edu.pe/SoftProductionsWS/insertarSerieTVResp" +
            "onse")]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.insertarSerieTVResponse> insertarSerieTVAsync(SoftProductions.SoftProductionsWS.insertarSerieTVRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class director : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoDirectorField;
        
        private int idDirectorField;
        
        private string nacionalidadField;
        
        private string nombreDirectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoDirector {
            get {
                return this.apellidoDirectorField;
            }
            set {
                this.apellidoDirectorField = value;
                this.RaisePropertyChanged("apellidoDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDirector {
            get {
                return this.idDirectorField;
            }
            set {
                this.idDirectorField = value;
                this.RaisePropertyChanged("idDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreDirector {
            get {
                return this.nombreDirectorField;
            }
            set {
                this.nombreDirectorField = value;
                this.RaisePropertyChanged("nombreDirector");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class serieTelevision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private capitulo[] capitulosField;
        
        private double costoProduccionField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private int idSerieTelevisionField;
        
        private ushort idiomaField;
        
        private string nombreSerieField;
        
        private byte[] portadaField;
        
        private productora productoraField;
        
        private string sipnosisField;
        
        private int temporadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("capitulos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public capitulo[] capitulos {
            get {
                return this.capitulosField;
            }
            set {
                this.capitulosField = value;
                this.RaisePropertyChanged("capitulos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costoProduccion {
            get {
                return this.costoProduccionField;
            }
            set {
                this.costoProduccionField = value;
                this.RaisePropertyChanged("costoProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSerieTelevision {
            get {
                return this.idSerieTelevisionField;
            }
            set {
                this.idSerieTelevisionField = value;
                this.RaisePropertyChanged("idSerieTelevision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreSerie {
            get {
                return this.nombreSerieField;
            }
            set {
                this.nombreSerieField = value;
                this.RaisePropertyChanged("nombreSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public productora productora {
            get {
                return this.productoraField;
            }
            set {
                this.productoraField = value;
                this.RaisePropertyChanged("productora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sipnosis {
            get {
                return this.sipnosisField;
            }
            set {
                this.sipnosisField = value;
                this.RaisePropertyChanged("sipnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int temporada {
            get {
                return this.temporadaField;
            }
            set {
                this.temporadaField = value;
                this.RaisePropertyChanged("temporada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class capitulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private director directorField;
        
        private string duracionField;
        
        private int idCapituloField;
        
        private string nombreCapituloField;
        
        private int numeroCapituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public director director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCapitulo {
            get {
                return this.idCapituloField;
            }
            set {
                this.idCapituloField = value;
                this.RaisePropertyChanged("idCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreCapitulo {
            get {
                return this.nombreCapituloField;
            }
            set {
                this.nombreCapituloField = value;
                this.RaisePropertyChanged("nombreCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroCapitulo {
            get {
                return this.numeroCapituloField;
            }
            set {
                this.numeroCapituloField = value;
                this.RaisePropertyChanged("numeroCapitulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softproductions.pucp.edu.pe/")]
    public partial class productora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private int bField;
        
        private int gField;
        
        private int idProductoraField;
        
        private byte[] logoField;
        
        private string nombreProductoraField;
        
        private int rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
                this.RaisePropertyChanged("b");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
                this.RaisePropertyChanged("g");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProductora {
            get {
                return this.idProductoraField;
            }
            set {
                this.idProductoraField = value;
                this.RaisePropertyChanged("idProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("logo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreProductora {
            get {
                return this.nombreProductoraField;
            }
            set {
                this.nombreProductoraField = value;
                this.RaisePropertyChanged("nombreProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
                this.RaisePropertyChanged("r");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDirectores", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDirectoresRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarTodosDirectoresRequest() {
        }
        
        public listarTodosDirectoresRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodosDirectoresResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodosDirectoresResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWS.director[] @return;
        
        public listarTodosDirectoresResponse() {
        }
        
        public listarTodosDirectoresResponse(SoftProductions.SoftProductionsWS.director[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductoras", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasProductorasRequest {
        
        public listarTodasProductorasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasProductorasResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasProductorasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWS.productora[] @return;
        
        public listarTodasProductorasResponse() {
        }
        
        public listarTodasProductorasResponse(SoftProductions.SoftProductionsWS.productora[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCapitulosXID", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCapitulosXIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSerie;
        
        public listarCapitulosXIDRequest() {
        }
        
        public listarCapitulosXIDRequest(int idSerie) {
            this.idSerie = idSerie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarCapitulosXIDResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarCapitulosXIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWS.capitulo[] @return;
        
        public listarCapitulosXIDResponse() {
        }
        
        public listarCapitulosXIDResponse(SoftProductions.SoftProductionsWS.capitulo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSeriesXNombre", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSeriesXNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarSeriesXNombreRequest() {
        }
        
        public listarSeriesXNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarSeriesXNombreResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarSeriesXNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWS.serieTelevision[] @return;
        
        public listarSeriesXNombreResponse() {
        }
        
        public listarSeriesXNombreResponse(SoftProductions.SoftProductionsWS.serieTelevision[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerieTV", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieTVRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.SoftProductionsWS.serieTelevision serie;
        
        public insertarSerieTVRequest() {
        }
        
        public insertarSerieTVRequest(SoftProductions.SoftProductionsWS.serieTelevision serie) {
            this.serie = serie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerieTVResponse", WrapperNamespace="http://services.softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieTVResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSerieTVResponse() {
        }
        
        public insertarSerieTVResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoftProductionsWSChannel : SoftProductions.SoftProductionsWS.SoftProductionsWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoftProductionsWSClient : System.ServiceModel.ClientBase<SoftProductions.SoftProductionsWS.SoftProductionsWS>, SoftProductions.SoftProductionsWS.SoftProductionsWS {
        
        public SoftProductionsWSClient() {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftProductionsWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoftProductionsWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse SoftProductions.SoftProductionsWS.SoftProductionsWS.listarTodosDirectores(SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest request) {
            return base.Channel.listarTodosDirectores(request);
        }
        
        public SoftProductions.SoftProductionsWS.director[] listarTodosDirectores(string nombre) {
            SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest inValue = new SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest();
            inValue.nombre = nombre;
            SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse retVal = ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarTodosDirectores(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse> SoftProductions.SoftProductionsWS.SoftProductionsWS.listarTodosDirectoresAsync(SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest request) {
            return base.Channel.listarTodosDirectoresAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodosDirectoresResponse> listarTodosDirectoresAsync(string nombre) {
            SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest inValue = new SoftProductions.SoftProductionsWS.listarTodosDirectoresRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarTodosDirectoresAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWS.listarTodasProductorasResponse SoftProductions.SoftProductionsWS.SoftProductionsWS.listarTodasProductoras(SoftProductions.SoftProductionsWS.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductoras(request);
        }
        
        public SoftProductions.SoftProductionsWS.productora[] listarTodasProductoras() {
            SoftProductions.SoftProductionsWS.listarTodasProductorasRequest inValue = new SoftProductions.SoftProductionsWS.listarTodasProductorasRequest();
            SoftProductions.SoftProductionsWS.listarTodasProductorasResponse retVal = ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarTodasProductoras(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodasProductorasResponse> SoftProductions.SoftProductionsWS.SoftProductionsWS.listarTodasProductorasAsync(SoftProductions.SoftProductionsWS.listarTodasProductorasRequest request) {
            return base.Channel.listarTodasProductorasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarTodasProductorasResponse> listarTodasProductorasAsync() {
            SoftProductions.SoftProductionsWS.listarTodasProductorasRequest inValue = new SoftProductions.SoftProductionsWS.listarTodasProductorasRequest();
            return ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarTodasProductorasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse SoftProductions.SoftProductionsWS.SoftProductionsWS.listarCapitulosXID(SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest request) {
            return base.Channel.listarCapitulosXID(request);
        }
        
        public SoftProductions.SoftProductionsWS.capitulo[] listarCapitulosXID(int idSerie) {
            SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest inValue = new SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest();
            inValue.idSerie = idSerie;
            SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse retVal = ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarCapitulosXID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse> SoftProductions.SoftProductionsWS.SoftProductionsWS.listarCapitulosXIDAsync(SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest request) {
            return base.Channel.listarCapitulosXIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarCapitulosXIDResponse> listarCapitulosXIDAsync(int idSerie) {
            SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest inValue = new SoftProductions.SoftProductionsWS.listarCapitulosXIDRequest();
            inValue.idSerie = idSerie;
            return ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarCapitulosXIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse SoftProductions.SoftProductionsWS.SoftProductionsWS.listarSeriesXNombre(SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest request) {
            return base.Channel.listarSeriesXNombre(request);
        }
        
        public SoftProductions.SoftProductionsWS.serieTelevision[] listarSeriesXNombre(string nombre) {
            SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest inValue = new SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest();
            inValue.nombre = nombre;
            SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse retVal = ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarSeriesXNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse> SoftProductions.SoftProductionsWS.SoftProductionsWS.listarSeriesXNombreAsync(SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest request) {
            return base.Channel.listarSeriesXNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.listarSeriesXNombreResponse> listarSeriesXNombreAsync(string nombre) {
            SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest inValue = new SoftProductions.SoftProductionsWS.listarSeriesXNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).listarSeriesXNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.SoftProductionsWS.insertarSerieTVResponse SoftProductions.SoftProductionsWS.SoftProductionsWS.insertarSerieTV(SoftProductions.SoftProductionsWS.insertarSerieTVRequest request) {
            return base.Channel.insertarSerieTV(request);
        }
        
        public int insertarSerieTV(SoftProductions.SoftProductionsWS.serieTelevision serie) {
            SoftProductions.SoftProductionsWS.insertarSerieTVRequest inValue = new SoftProductions.SoftProductionsWS.insertarSerieTVRequest();
            inValue.serie = serie;
            SoftProductions.SoftProductionsWS.insertarSerieTVResponse retVal = ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).insertarSerieTV(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.insertarSerieTVResponse> SoftProductions.SoftProductionsWS.SoftProductionsWS.insertarSerieTVAsync(SoftProductions.SoftProductionsWS.insertarSerieTVRequest request) {
            return base.Channel.insertarSerieTVAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.SoftProductionsWS.insertarSerieTVResponse> insertarSerieTVAsync(SoftProductions.SoftProductionsWS.serieTelevision serie) {
            SoftProductions.SoftProductionsWS.insertarSerieTVRequest inValue = new SoftProductions.SoftProductionsWS.insertarSerieTVRequest();
            inValue.serie = serie;
            return ((SoftProductions.SoftProductionsWS.SoftProductionsWS)(this)).insertarSerieTVAsync(inValue);
        }
    }
}
