//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftProductions.ProductoraWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://softproductions.pucp.edu.pe/", ConfigurationName="ProductoraWS.ProductoraWS")]
    public interface ProductoraWS {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarProductorasTodasRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarProductorasTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.ProductoraWS.listarProductorasTodasResponse listarProductorasTodas(SoftProductions.ProductoraWS.listarProductorasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarProductorasTodasRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarProductorasTodasResponse")]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarProductorasTodasResponse> listarProductorasTodasAsync(SoftProductions.ProductoraWS.listarProductorasTodasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarDirectorPorNombreRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarDirectorPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.ProductoraWS.listarDirectorPorNombreResponse listarDirectorPorNombre(SoftProductions.ProductoraWS.listarDirectorPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarDirectorPorNombreRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarDirectorPorNombreResponse")]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarDirectorPorNombreResponse> listarDirectorPorNombreAsync(SoftProductions.ProductoraWS.listarDirectorPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorNombreRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorNombreResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.ProductoraWS.listarPorNombreResponse listarPorNombre(SoftProductions.ProductoraWS.listarPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorNombreRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorNombreResponse")]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorNombreResponse> listarPorNombreAsync(SoftProductions.ProductoraWS.listarPorNombreRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorIdSerieRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorIdSerieResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.ProductoraWS.listarPorIdSerieResponse listarPorIdSerie(SoftProductions.ProductoraWS.listarPorIdSerieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorIdSerieRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/listarPorIdSerieResponse")]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorIdSerieResponse> listarPorIdSerieAsync(SoftProductions.ProductoraWS.listarPorIdSerieRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/insertarSerieTelevisionRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/insertarSerieTelevisionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftProductions.ProductoraWS.insertarSerieTelevisionResponse insertarSerieTelevision(SoftProductions.ProductoraWS.insertarSerieTelevisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://softproductions.pucp.edu.pe/ProductoraWS/insertarSerieTelevisionRequest", ReplyAction="http://softproductions.pucp.edu.pe/ProductoraWS/insertarSerieTelevisionResponse")]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.insertarSerieTelevisionResponse> insertarSerieTelevisionAsync(SoftProductions.ProductoraWS.insertarSerieTelevisionRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softproductions.pucp.edu.pe/")]
    public partial class productora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private int bField;
        
        private int gField;
        
        private int idProductoraField;
        
        private byte[] logoField;
        
        private string nombreProductoraField;
        
        private int rField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int b {
            get {
                return this.bField;
            }
            set {
                this.bField = value;
                this.RaisePropertyChanged("b");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int g {
            get {
                return this.gField;
            }
            set {
                this.gField = value;
                this.RaisePropertyChanged("g");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idProductora {
            get {
                return this.idProductoraField;
            }
            set {
                this.idProductoraField = value;
                this.RaisePropertyChanged("idProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=4)]
        public byte[] logo {
            get {
                return this.logoField;
            }
            set {
                this.logoField = value;
                this.RaisePropertyChanged("logo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombreProductora {
            get {
                return this.nombreProductoraField;
            }
            set {
                this.nombreProductoraField = value;
                this.RaisePropertyChanged("nombreProductora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int r {
            get {
                return this.rField;
            }
            set {
                this.rField = value;
                this.RaisePropertyChanged("r");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softproductions.pucp.edu.pe/")]
    public partial class capitulo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private director directorField;
        
        private string duracionField;
        
        private int idCapituloField;
        
        private string nombreCapituloField;
        
        private int numeroCapituloField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public director director {
            get {
                return this.directorField;
            }
            set {
                this.directorField = value;
                this.RaisePropertyChanged("director");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string duracion {
            get {
                return this.duracionField;
            }
            set {
                this.duracionField = value;
                this.RaisePropertyChanged("duracion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idCapitulo {
            get {
                return this.idCapituloField;
            }
            set {
                this.idCapituloField = value;
                this.RaisePropertyChanged("idCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreCapitulo {
            get {
                return this.nombreCapituloField;
            }
            set {
                this.nombreCapituloField = value;
                this.RaisePropertyChanged("nombreCapitulo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int numeroCapitulo {
            get {
                return this.numeroCapituloField;
            }
            set {
                this.numeroCapituloField = value;
                this.RaisePropertyChanged("numeroCapitulo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softproductions.pucp.edu.pe/")]
    public partial class director : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string apellidoDirectorField;
        
        private int idDirectorField;
        
        private string nacionalidadField;
        
        private string nombreDirectorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string apellidoDirector {
            get {
                return this.apellidoDirectorField;
            }
            set {
                this.apellidoDirectorField = value;
                this.RaisePropertyChanged("apellidoDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idDirector {
            get {
                return this.idDirectorField;
            }
            set {
                this.idDirectorField = value;
                this.RaisePropertyChanged("idDirector");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nombreDirector {
            get {
                return this.nombreDirectorField;
            }
            set {
                this.nombreDirectorField = value;
                this.RaisePropertyChanged("nombreDirector");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://softproductions.pucp.edu.pe/")]
    public partial class serieTelevision : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private capitulo[] capitulosField;
        
        private double costoProduccionField;
        
        private System.DateTime fechaEmisionField;
        
        private bool fechaEmisionFieldSpecified;
        
        private int idSerieTelevisionField;
        
        private ushort idiomaField;
        
        private string nombreSerieField;
        
        private byte[] portadaField;
        
        private productora productoraField;
        
        private string sipnosisField;
        
        private int temporadaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("capitulos", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public capitulo[] capitulos {
            get {
                return this.capitulosField;
            }
            set {
                this.capitulosField = value;
                this.RaisePropertyChanged("capitulos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costoProduccion {
            get {
                return this.costoProduccionField;
            }
            set {
                this.costoProduccionField = value;
                this.RaisePropertyChanged("costoProduccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaEmision {
            get {
                return this.fechaEmisionField;
            }
            set {
                this.fechaEmisionField = value;
                this.RaisePropertyChanged("fechaEmision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEmisionSpecified {
            get {
                return this.fechaEmisionFieldSpecified;
            }
            set {
                this.fechaEmisionFieldSpecified = value;
                this.RaisePropertyChanged("fechaEmisionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idSerieTelevision {
            get {
                return this.idSerieTelevisionField;
            }
            set {
                this.idSerieTelevisionField = value;
                this.RaisePropertyChanged("idSerieTelevision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public ushort idioma {
            get {
                return this.idiomaField;
            }
            set {
                this.idiomaField = value;
                this.RaisePropertyChanged("idioma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombreSerie {
            get {
                return this.nombreSerieField;
            }
            set {
                this.nombreSerieField = value;
                this.RaisePropertyChanged("nombreSerie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public productora productora {
            get {
                return this.productoraField;
            }
            set {
                this.productoraField = value;
                this.RaisePropertyChanged("productora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string sipnosis {
            get {
                return this.sipnosisField;
            }
            set {
                this.sipnosisField = value;
                this.RaisePropertyChanged("sipnosis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int temporada {
            get {
                return this.temporadaField;
            }
            set {
                this.temporadaField = value;
                this.RaisePropertyChanged("temporada");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductorasTodas", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductorasTodasRequest {
        
        public listarProductorasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarProductorasTodasResponse", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarProductorasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.ProductoraWS.productora[] @return;
        
        public listarProductorasTodasResponse() {
        }
        
        public listarProductorasTodasResponse(SoftProductions.ProductoraWS.productora[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectorPorNombre", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectorPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarDirectorPorNombreRequest() {
        }
        
        public listarDirectorPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDirectorPorNombreResponse", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDirectorPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.ProductoraWS.director[] @return;
        
        public listarDirectorPorNombreResponse() {
        }
        
        public listarDirectorPorNombreResponse(SoftProductions.ProductoraWS.director[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombre", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarPorNombreRequest() {
        }
        
        public listarPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorNombreResponse", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.ProductoraWS.serieTelevision[] @return;
        
        public listarPorNombreResponse() {
        }
        
        public listarPorNombreResponse(SoftProductions.ProductoraWS.serieTelevision[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorIdSerie", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorIdSerieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idSerie;
        
        public listarPorIdSerieRequest() {
        }
        
        public listarPorIdSerieRequest(int idSerie) {
            this.idSerie = idSerie;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPorIdSerieResponse", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarPorIdSerieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.ProductoraWS.capitulo[] @return;
        
        public listarPorIdSerieResponse() {
        }
        
        public listarPorIdSerieResponse(SoftProductions.ProductoraWS.capitulo[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerieTelevision", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieTelevisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftProductions.ProductoraWS.serieTelevision serieTelevision;
        
        public insertarSerieTelevisionRequest() {
        }
        
        public insertarSerieTelevisionRequest(SoftProductions.ProductoraWS.serieTelevision serieTelevision) {
            this.serieTelevision = serieTelevision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarSerieTelevisionResponse", WrapperNamespace="http://softproductions.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarSerieTelevisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://softproductions.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarSerieTelevisionResponse() {
        }
        
        public insertarSerieTelevisionResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProductoraWSChannel : SoftProductions.ProductoraWS.ProductoraWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProductoraWSClient : System.ServiceModel.ClientBase<SoftProductions.ProductoraWS.ProductoraWS>, SoftProductions.ProductoraWS.ProductoraWS {
        
        public ProductoraWSClient() {
        }
        
        public ProductoraWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProductoraWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoraWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProductoraWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.ProductoraWS.listarProductorasTodasResponse SoftProductions.ProductoraWS.ProductoraWS.listarProductorasTodas(SoftProductions.ProductoraWS.listarProductorasTodasRequest request) {
            return base.Channel.listarProductorasTodas(request);
        }
        
        public SoftProductions.ProductoraWS.productora[] listarProductorasTodas() {
            SoftProductions.ProductoraWS.listarProductorasTodasRequest inValue = new SoftProductions.ProductoraWS.listarProductorasTodasRequest();
            SoftProductions.ProductoraWS.listarProductorasTodasResponse retVal = ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarProductorasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarProductorasTodasResponse> SoftProductions.ProductoraWS.ProductoraWS.listarProductorasTodasAsync(SoftProductions.ProductoraWS.listarProductorasTodasRequest request) {
            return base.Channel.listarProductorasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarProductorasTodasResponse> listarProductorasTodasAsync() {
            SoftProductions.ProductoraWS.listarProductorasTodasRequest inValue = new SoftProductions.ProductoraWS.listarProductorasTodasRequest();
            return ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarProductorasTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.ProductoraWS.listarDirectorPorNombreResponse SoftProductions.ProductoraWS.ProductoraWS.listarDirectorPorNombre(SoftProductions.ProductoraWS.listarDirectorPorNombreRequest request) {
            return base.Channel.listarDirectorPorNombre(request);
        }
        
        public SoftProductions.ProductoraWS.director[] listarDirectorPorNombre(string nombre) {
            SoftProductions.ProductoraWS.listarDirectorPorNombreRequest inValue = new SoftProductions.ProductoraWS.listarDirectorPorNombreRequest();
            inValue.nombre = nombre;
            SoftProductions.ProductoraWS.listarDirectorPorNombreResponse retVal = ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarDirectorPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarDirectorPorNombreResponse> SoftProductions.ProductoraWS.ProductoraWS.listarDirectorPorNombreAsync(SoftProductions.ProductoraWS.listarDirectorPorNombreRequest request) {
            return base.Channel.listarDirectorPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarDirectorPorNombreResponse> listarDirectorPorNombreAsync(string nombre) {
            SoftProductions.ProductoraWS.listarDirectorPorNombreRequest inValue = new SoftProductions.ProductoraWS.listarDirectorPorNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarDirectorPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.ProductoraWS.listarPorNombreResponse SoftProductions.ProductoraWS.ProductoraWS.listarPorNombre(SoftProductions.ProductoraWS.listarPorNombreRequest request) {
            return base.Channel.listarPorNombre(request);
        }
        
        public SoftProductions.ProductoraWS.serieTelevision[] listarPorNombre(string nombre) {
            SoftProductions.ProductoraWS.listarPorNombreRequest inValue = new SoftProductions.ProductoraWS.listarPorNombreRequest();
            inValue.nombre = nombre;
            SoftProductions.ProductoraWS.listarPorNombreResponse retVal = ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorNombreResponse> SoftProductions.ProductoraWS.ProductoraWS.listarPorNombreAsync(SoftProductions.ProductoraWS.listarPorNombreRequest request) {
            return base.Channel.listarPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorNombreResponse> listarPorNombreAsync(string nombre) {
            SoftProductions.ProductoraWS.listarPorNombreRequest inValue = new SoftProductions.ProductoraWS.listarPorNombreRequest();
            inValue.nombre = nombre;
            return ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.ProductoraWS.listarPorIdSerieResponse SoftProductions.ProductoraWS.ProductoraWS.listarPorIdSerie(SoftProductions.ProductoraWS.listarPorIdSerieRequest request) {
            return base.Channel.listarPorIdSerie(request);
        }
        
        public SoftProductions.ProductoraWS.capitulo[] listarPorIdSerie(int idSerie) {
            SoftProductions.ProductoraWS.listarPorIdSerieRequest inValue = new SoftProductions.ProductoraWS.listarPorIdSerieRequest();
            inValue.idSerie = idSerie;
            SoftProductions.ProductoraWS.listarPorIdSerieResponse retVal = ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarPorIdSerie(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorIdSerieResponse> SoftProductions.ProductoraWS.ProductoraWS.listarPorIdSerieAsync(SoftProductions.ProductoraWS.listarPorIdSerieRequest request) {
            return base.Channel.listarPorIdSerieAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.ProductoraWS.listarPorIdSerieResponse> listarPorIdSerieAsync(int idSerie) {
            SoftProductions.ProductoraWS.listarPorIdSerieRequest inValue = new SoftProductions.ProductoraWS.listarPorIdSerieRequest();
            inValue.idSerie = idSerie;
            return ((SoftProductions.ProductoraWS.ProductoraWS)(this)).listarPorIdSerieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftProductions.ProductoraWS.insertarSerieTelevisionResponse SoftProductions.ProductoraWS.ProductoraWS.insertarSerieTelevision(SoftProductions.ProductoraWS.insertarSerieTelevisionRequest request) {
            return base.Channel.insertarSerieTelevision(request);
        }
        
        public int insertarSerieTelevision(SoftProductions.ProductoraWS.serieTelevision serieTelevision) {
            SoftProductions.ProductoraWS.insertarSerieTelevisionRequest inValue = new SoftProductions.ProductoraWS.insertarSerieTelevisionRequest();
            inValue.serieTelevision = serieTelevision;
            SoftProductions.ProductoraWS.insertarSerieTelevisionResponse retVal = ((SoftProductions.ProductoraWS.ProductoraWS)(this)).insertarSerieTelevision(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftProductions.ProductoraWS.insertarSerieTelevisionResponse> SoftProductions.ProductoraWS.ProductoraWS.insertarSerieTelevisionAsync(SoftProductions.ProductoraWS.insertarSerieTelevisionRequest request) {
            return base.Channel.insertarSerieTelevisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftProductions.ProductoraWS.insertarSerieTelevisionResponse> insertarSerieTelevisionAsync(SoftProductions.ProductoraWS.serieTelevision serieTelevision) {
            SoftProductions.ProductoraWS.insertarSerieTelevisionRequest inValue = new SoftProductions.ProductoraWS.insertarSerieTelevisionRequest();
            inValue.serieTelevision = serieTelevision;
            return ((SoftProductions.ProductoraWS.ProductoraWS)(this)).insertarSerieTelevisionAsync(inValue);
        }
    }
}
