//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventSoft.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", ConfigurationName="ServicioWeb.ServicioWeb")]
    public interface ServicioWeb {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarEstablecimientosPorNombre" +
            "Request", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarEstablecimientosPorNombre" +
            "Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse listarEstablecimientosPorNombre(EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarEstablecimientosPorNombre" +
            "Request", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarEstablecimientosPorNombre" +
            "Response")]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse> listarEstablecimientosPorNombreAsync(EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/insertarEventoRequest", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/insertarEventoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServicioWeb.insertarEventoResponse insertarEvento(EventSoft.ServicioWeb.insertarEventoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/insertarEventoRequest", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/insertarEventoResponse")]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.insertarEventoResponse> insertarEventoAsync(EventSoft.ServicioWeb.insertarEventoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarArtistasPorNombreRequest", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarArtistasPorNombreResponse" +
            "")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EventSoft.ServicioWeb.listarArtistasPorNombreResponse listarArtistasPorNombre(EventSoft.ServicioWeb.listarArtistasPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarArtistasPorNombreRequest", ReplyAction="http://services.eventsoft.pucp.edu.pe/ServicioWeb/listarArtistasPorNombreResponse" +
            "")]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarArtistasPorNombreResponse> listarArtistasPorNombreAsync(EventSoft.ServicioWeb.listarArtistasPorNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/")]
    public partial class establecimiento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private int capacidadAsientosField;
        
        private int idEstablecimientoField;
        
        private string nombreField;
        
        private bool tieneEstacionamientoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int capacidadAsientos {
            get {
                return this.capacidadAsientosField;
            }
            set {
                this.capacidadAsientosField = value;
                this.RaisePropertyChanged("capacidadAsientos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idEstablecimiento {
            get {
                return this.idEstablecimientoField;
            }
            set {
                this.idEstablecimientoField = value;
                this.RaisePropertyChanged("idEstablecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public bool tieneEstacionamiento {
            get {
                return this.tieneEstacionamientoField;
            }
            set {
                this.tieneEstacionamientoField = value;
                this.RaisePropertyChanged("tieneEstacionamiento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/")]
    public partial class artista : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idArtistaField;
        
        private string nacionalidadField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idArtista {
            get {
                return this.idArtistaField;
            }
            set {
                this.idArtistaField = value;
                this.RaisePropertyChanged("idArtista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nacionalidad {
            get {
                return this.nacionalidadField;
            }
            set {
                this.nacionalidadField = value;
                this.RaisePropertyChanged("nacionalidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/")]
    public partial class evento : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private artista artistaField;
        
        private int cantidadEntradasDisponiblesField;
        
        private double costoRealizacionField;
        
        private string descripcionField;
        
        private establecimiento establecimientoField;
        
        private System.DateTime fechaEventoField;
        
        private bool fechaEventoFieldSpecified;
        
        private byte[] fotoField;
        
        private string horaEventoField;
        
        private int idEventoField;
        
        private string nombreField;
        
        private tipoEvento tipoEventoField;
        
        private bool tipoEventoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public artista artista {
            get {
                return this.artistaField;
            }
            set {
                this.artistaField = value;
                this.RaisePropertyChanged("artista");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int cantidadEntradasDisponibles {
            get {
                return this.cantidadEntradasDisponiblesField;
            }
            set {
                this.cantidadEntradasDisponiblesField = value;
                this.RaisePropertyChanged("cantidadEntradasDisponibles");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public double costoRealizacion {
            get {
                return this.costoRealizacionField;
            }
            set {
                this.costoRealizacionField = value;
                this.RaisePropertyChanged("costoRealizacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public establecimiento establecimiento {
            get {
                return this.establecimientoField;
            }
            set {
                this.establecimientoField = value;
                this.RaisePropertyChanged("establecimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public System.DateTime fechaEvento {
            get {
                return this.fechaEventoField;
            }
            set {
                this.fechaEventoField = value;
                this.RaisePropertyChanged("fechaEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaEventoSpecified {
            get {
                return this.fechaEventoFieldSpecified;
            }
            set {
                this.fechaEventoFieldSpecified = value;
                this.RaisePropertyChanged("fechaEventoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string horaEvento {
            get {
                return this.horaEventoField;
            }
            set {
                this.horaEventoField = value;
                this.RaisePropertyChanged("horaEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public int idEvento {
            get {
                return this.idEventoField;
            }
            set {
                this.idEventoField = value;
                this.RaisePropertyChanged("idEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public tipoEvento tipoEvento {
            get {
                return this.tipoEventoField;
            }
            set {
                this.tipoEventoField = value;
                this.RaisePropertyChanged("tipoEvento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoEventoSpecified {
            get {
                return this.tipoEventoFieldSpecified;
            }
            set {
                this.tipoEventoFieldSpecified = value;
                this.RaisePropertyChanged("tipoEventoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/")]
    public enum tipoEvento {
        
        /// <remarks/>
        CONCIERTO,
        
        /// <remarks/>
        TEATRO,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstablecimientosPorNombre", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEstablecimientosPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarEstablecimientosPorNombreRequest() {
        }
        
        public listarEstablecimientosPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarEstablecimientosPorNombreResponse", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarEstablecimientosPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServicioWeb.establecimiento[] @return;
        
        public listarEstablecimientosPorNombreResponse() {
        }
        
        public listarEstablecimientosPorNombreResponse(EventSoft.ServicioWeb.establecimiento[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEvento", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServicioWeb.evento evento;
        
        public insertarEventoRequest() {
        }
        
        public insertarEventoRequest(EventSoft.ServicioWeb.evento evento) {
            this.evento = evento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarEventoResponse", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarEventoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarEventoResponse() {
        }
        
        public insertarEventoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarArtistasPorNombre", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarArtistasPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarArtistasPorNombreRequest() {
        }
        
        public listarArtistasPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarArtistasPorNombreResponse", WrapperNamespace="http://services.eventsoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarArtistasPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.eventsoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EventSoft.ServicioWeb.artista[] @return;
        
        public listarArtistasPorNombreResponse() {
        }
        
        public listarArtistasPorNombreResponse(EventSoft.ServicioWeb.artista[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWebChannel : EventSoft.ServicioWeb.ServicioWeb, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWebClient : System.ServiceModel.ClientBase<EventSoft.ServicioWeb.ServicioWeb>, EventSoft.ServicioWeb.ServicioWeb {
        
        public ServicioWebClient() {
        }
        
        public ServicioWebClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWebClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse EventSoft.ServicioWeb.ServicioWeb.listarEstablecimientosPorNombre(EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest request) {
            return base.Channel.listarEstablecimientosPorNombre(request);
        }
        
        public EventSoft.ServicioWeb.establecimiento[] listarEstablecimientosPorNombre(string nombre) {
            EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest inValue = new EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest();
            inValue.nombre = nombre;
            EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse retVal = ((EventSoft.ServicioWeb.ServicioWeb)(this)).listarEstablecimientosPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse> EventSoft.ServicioWeb.ServicioWeb.listarEstablecimientosPorNombreAsync(EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest request) {
            return base.Channel.listarEstablecimientosPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarEstablecimientosPorNombreResponse> listarEstablecimientosPorNombreAsync(string nombre) {
            EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest inValue = new EventSoft.ServicioWeb.listarEstablecimientosPorNombreRequest();
            inValue.nombre = nombre;
            return ((EventSoft.ServicioWeb.ServicioWeb)(this)).listarEstablecimientosPorNombreAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServicioWeb.insertarEventoResponse EventSoft.ServicioWeb.ServicioWeb.insertarEvento(EventSoft.ServicioWeb.insertarEventoRequest request) {
            return base.Channel.insertarEvento(request);
        }
        
        public int insertarEvento(EventSoft.ServicioWeb.evento evento) {
            EventSoft.ServicioWeb.insertarEventoRequest inValue = new EventSoft.ServicioWeb.insertarEventoRequest();
            inValue.evento = evento;
            EventSoft.ServicioWeb.insertarEventoResponse retVal = ((EventSoft.ServicioWeb.ServicioWeb)(this)).insertarEvento(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.insertarEventoResponse> EventSoft.ServicioWeb.ServicioWeb.insertarEventoAsync(EventSoft.ServicioWeb.insertarEventoRequest request) {
            return base.Channel.insertarEventoAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServicioWeb.insertarEventoResponse> insertarEventoAsync(EventSoft.ServicioWeb.evento evento) {
            EventSoft.ServicioWeb.insertarEventoRequest inValue = new EventSoft.ServicioWeb.insertarEventoRequest();
            inValue.evento = evento;
            return ((EventSoft.ServicioWeb.ServicioWeb)(this)).insertarEventoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EventSoft.ServicioWeb.listarArtistasPorNombreResponse EventSoft.ServicioWeb.ServicioWeb.listarArtistasPorNombre(EventSoft.ServicioWeb.listarArtistasPorNombreRequest request) {
            return base.Channel.listarArtistasPorNombre(request);
        }
        
        public EventSoft.ServicioWeb.artista[] listarArtistasPorNombre(string nombre) {
            EventSoft.ServicioWeb.listarArtistasPorNombreRequest inValue = new EventSoft.ServicioWeb.listarArtistasPorNombreRequest();
            inValue.nombre = nombre;
            EventSoft.ServicioWeb.listarArtistasPorNombreResponse retVal = ((EventSoft.ServicioWeb.ServicioWeb)(this)).listarArtistasPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarArtistasPorNombreResponse> EventSoft.ServicioWeb.ServicioWeb.listarArtistasPorNombreAsync(EventSoft.ServicioWeb.listarArtistasPorNombreRequest request) {
            return base.Channel.listarArtistasPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<EventSoft.ServicioWeb.listarArtistasPorNombreResponse> listarArtistasPorNombreAsync(string nombre) {
            EventSoft.ServicioWeb.listarArtistasPorNombreRequest inValue = new EventSoft.ServicioWeb.listarArtistasPorNombreRequest();
            inValue.nombre = nombre;
            return ((EventSoft.ServicioWeb.ServicioWeb)(this)).listarArtistasPorNombreAsync(inValue);
        }
    }
}
