//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameSoft.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", ConfigurationName="ServicioWS.ServicioWS")]
    public interface ServicioWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/insertarVideojuegoRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/insertarVideojuegoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWS.insertarVideojuegoResponse insertarVideojuego(GameSoft.ServicioWS.insertarVideojuegoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/insertarVideojuegoRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/insertarVideojuegoResponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.insertarVideojuegoResponse> insertarVideojuegoAsync(GameSoft.ServicioWS.insertarVideojuegoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarTodasGenerosRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarTodasGenerosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWS.listarTodasGenerosResponse listarTodasGeneros(GameSoft.ServicioWS.listarTodasGenerosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarTodasGenerosRequest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarTodasGenerosResponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.listarTodasGenerosResponse> listarTodasGenerosAsync(GameSoft.ServicioWS.listarTodasGenerosRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarDesarrolladorasPorNombreReq" +
            "uest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarDesarrolladorasPorNombreRes" +
            "ponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse listarDesarrolladorasPorNombre(GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarDesarrolladorasPorNombreReq" +
            "uest", ReplyAction="http://services.gamesoft.pucp.edu.pe/ServicioWS/listarDesarrolladorasPorNombreRes" +
            "ponse")]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse> listarDesarrolladorasPorNombreAsync(GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class videojuego : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private ushort clasificacionESRBField;
        
        private double costoDesarrolloField;
        
        private desarrolladora desarrolladoraField;
        
        private System.DateTime fechaLanzamientoField;
        
        private bool fechaLanzamientoFieldSpecified;
        
        private genero generoField;
        
        private int idVideojuegoField;
        
        private byte[] materialPromocionalPDFField;
        
        private string nombreField;
        
        private byte[] portadaField;
        
        private bool versionNintendoSwitchField;
        
        private bool versionPCField;
        
        private bool versionPlaystation5Field;
        
        private bool versionSmartphoneField;
        
        private bool versionXboxSeriesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public ushort clasificacionESRB {
            get {
                return this.clasificacionESRBField;
            }
            set {
                this.clasificacionESRBField = value;
                this.RaisePropertyChanged("clasificacionESRB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public double costoDesarrollo {
            get {
                return this.costoDesarrolloField;
            }
            set {
                this.costoDesarrolloField = value;
                this.RaisePropertyChanged("costoDesarrollo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public desarrolladora desarrolladora {
            get {
                return this.desarrolladoraField;
            }
            set {
                this.desarrolladoraField = value;
                this.RaisePropertyChanged("desarrolladora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaLanzamiento {
            get {
                return this.fechaLanzamientoField;
            }
            set {
                this.fechaLanzamientoField = value;
                this.RaisePropertyChanged("fechaLanzamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaLanzamientoSpecified {
            get {
                return this.fechaLanzamientoFieldSpecified;
            }
            set {
                this.fechaLanzamientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaLanzamientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public genero genero {
            get {
                return this.generoField;
            }
            set {
                this.generoField = value;
                this.RaisePropertyChanged("genero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public int idVideojuego {
            get {
                return this.idVideojuegoField;
            }
            set {
                this.idVideojuegoField = value;
                this.RaisePropertyChanged("idVideojuego");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=7)]
        public byte[] materialPromocionalPDF {
            get {
                return this.materialPromocionalPDFField;
            }
            set {
                this.materialPromocionalPDFField = value;
                this.RaisePropertyChanged("materialPromocionalPDF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=9)]
        public byte[] portada {
            get {
                return this.portadaField;
            }
            set {
                this.portadaField = value;
                this.RaisePropertyChanged("portada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public bool versionNintendoSwitch {
            get {
                return this.versionNintendoSwitchField;
            }
            set {
                this.versionNintendoSwitchField = value;
                this.RaisePropertyChanged("versionNintendoSwitch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public bool versionPC {
            get {
                return this.versionPCField;
            }
            set {
                this.versionPCField = value;
                this.RaisePropertyChanged("versionPC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public bool versionPlaystation5 {
            get {
                return this.versionPlaystation5Field;
            }
            set {
                this.versionPlaystation5Field = value;
                this.RaisePropertyChanged("versionPlaystation5");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public bool versionSmartphone {
            get {
                return this.versionSmartphoneField;
            }
            set {
                this.versionSmartphoneField = value;
                this.RaisePropertyChanged("versionSmartphone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public bool versionXboxSeries {
            get {
                return this.versionXboxSeriesField;
            }
            set {
                this.versionXboxSeriesField = value;
                this.RaisePropertyChanged("versionXboxSeries");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class desarrolladora : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idDesarrolladoraField;
        
        private string nombreField;
        
        private pais paisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idDesarrolladora {
            get {
                return this.idDesarrolladoraField;
            }
            set {
                this.idDesarrolladoraField = value;
                this.RaisePropertyChanged("idDesarrolladora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public pais pais {
            get {
                return this.paisField;
            }
            set {
                this.paisField = value;
                this.RaisePropertyChanged("pais");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class pais : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idPaisField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idPais {
            get {
                return this.idPaisField;
            }
            set {
                this.idPaisField = value;
                this.RaisePropertyChanged("idPais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/")]
    public partial class genero : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idGeneroField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idGenero {
            get {
                return this.idGeneroField;
            }
            set {
                this.idGeneroField = value;
                this.RaisePropertyChanged("idGenero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVideojuego", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVideojuegoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWS.videojuego videojuego;
        
        public insertarVideojuegoRequest() {
        }
        
        public insertarVideojuegoRequest(GameSoft.ServicioWS.videojuego videojuego) {
            this.videojuego = videojuego;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarVideojuegoResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarVideojuegoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarVideojuegoResponse() {
        }
        
        public insertarVideojuegoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasGeneros", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasGenerosRequest {
        
        public listarTodasGenerosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarTodasGenerosResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarTodasGenerosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWS.genero[] @return;
        
        public listarTodasGenerosResponse() {
        }
        
        public listarTodasGenerosResponse(GameSoft.ServicioWS.genero[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDesarrolladorasPorNombre", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDesarrolladorasPorNombreRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        public listarDesarrolladorasPorNombreRequest() {
        }
        
        public listarDesarrolladorasPorNombreRequest(string nombre) {
            this.nombre = nombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarDesarrolladorasPorNombreResponse", WrapperNamespace="http://services.gamesoft.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarDesarrolladorasPorNombreResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.gamesoft.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GameSoft.ServicioWS.desarrolladora[] @return;
        
        public listarDesarrolladorasPorNombreResponse() {
        }
        
        public listarDesarrolladorasPorNombreResponse(GameSoft.ServicioWS.desarrolladora[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicioWSChannel : GameSoft.ServicioWS.ServicioWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioWSClient : System.ServiceModel.ClientBase<GameSoft.ServicioWS.ServicioWS>, GameSoft.ServicioWS.ServicioWS {
        
        public ServicioWSClient() {
        }
        
        public ServicioWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWS.insertarVideojuegoResponse GameSoft.ServicioWS.ServicioWS.insertarVideojuego(GameSoft.ServicioWS.insertarVideojuegoRequest request) {
            return base.Channel.insertarVideojuego(request);
        }
        
        public int insertarVideojuego(GameSoft.ServicioWS.videojuego videojuego) {
            GameSoft.ServicioWS.insertarVideojuegoRequest inValue = new GameSoft.ServicioWS.insertarVideojuegoRequest();
            inValue.videojuego = videojuego;
            GameSoft.ServicioWS.insertarVideojuegoResponse retVal = ((GameSoft.ServicioWS.ServicioWS)(this)).insertarVideojuego(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.insertarVideojuegoResponse> GameSoft.ServicioWS.ServicioWS.insertarVideojuegoAsync(GameSoft.ServicioWS.insertarVideojuegoRequest request) {
            return base.Channel.insertarVideojuegoAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWS.insertarVideojuegoResponse> insertarVideojuegoAsync(GameSoft.ServicioWS.videojuego videojuego) {
            GameSoft.ServicioWS.insertarVideojuegoRequest inValue = new GameSoft.ServicioWS.insertarVideojuegoRequest();
            inValue.videojuego = videojuego;
            return ((GameSoft.ServicioWS.ServicioWS)(this)).insertarVideojuegoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWS.listarTodasGenerosResponse GameSoft.ServicioWS.ServicioWS.listarTodasGeneros(GameSoft.ServicioWS.listarTodasGenerosRequest request) {
            return base.Channel.listarTodasGeneros(request);
        }
        
        public GameSoft.ServicioWS.genero[] listarTodasGeneros() {
            GameSoft.ServicioWS.listarTodasGenerosRequest inValue = new GameSoft.ServicioWS.listarTodasGenerosRequest();
            GameSoft.ServicioWS.listarTodasGenerosResponse retVal = ((GameSoft.ServicioWS.ServicioWS)(this)).listarTodasGeneros(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.listarTodasGenerosResponse> GameSoft.ServicioWS.ServicioWS.listarTodasGenerosAsync(GameSoft.ServicioWS.listarTodasGenerosRequest request) {
            return base.Channel.listarTodasGenerosAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWS.listarTodasGenerosResponse> listarTodasGenerosAsync() {
            GameSoft.ServicioWS.listarTodasGenerosRequest inValue = new GameSoft.ServicioWS.listarTodasGenerosRequest();
            return ((GameSoft.ServicioWS.ServicioWS)(this)).listarTodasGenerosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse GameSoft.ServicioWS.ServicioWS.listarDesarrolladorasPorNombre(GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest request) {
            return base.Channel.listarDesarrolladorasPorNombre(request);
        }
        
        public GameSoft.ServicioWS.desarrolladora[] listarDesarrolladorasPorNombre(string nombre) {
            GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest inValue = new GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest();
            inValue.nombre = nombre;
            GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse retVal = ((GameSoft.ServicioWS.ServicioWS)(this)).listarDesarrolladorasPorNombre(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse> GameSoft.ServicioWS.ServicioWS.listarDesarrolladorasPorNombreAsync(GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest request) {
            return base.Channel.listarDesarrolladorasPorNombreAsync(request);
        }
        
        public System.Threading.Tasks.Task<GameSoft.ServicioWS.listarDesarrolladorasPorNombreResponse> listarDesarrolladorasPorNombreAsync(string nombre) {
            GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest inValue = new GameSoft.ServicioWS.listarDesarrolladorasPorNombreRequest();
            inValue.nombre = nombre;
            return ((GameSoft.ServicioWS.ServicioWS)(this)).listarDesarrolladorasPorNombreAsync(inValue);
        }
    }
}
